fix: bug of create visualization
BinaryStudioAcademy/bsa-2020-DaLi pull request #147
Opened 2020-08-26 07:23 UTC by serhiitaran

2020-08-26 09:03 UTC, YuriiStetsula requested changes

2020-08-26 09:03 UTC, YuriiStetsula commented on client/src/containers/ViewVisualizationContainer/sagas.js
> +  history.push('/');
add error handling

2020-08-26 12:12 UTC, serhiitaran commented on client/src/containers/ViewVisualizationContainer/sagas.js
> +  history.push('/');
> add error handling

done

2020-08-31 20:37 UTC, YuriiStetsula approved these changes

2020-09-08 19:12 UTC, merged