Feature/linechart & barchart multiline
BinaryStudioAcademy/bsa-2020-DaLi pull request #183
Opened 2020-08-31 14:56 UTC by tarkus2000ua

2020-08-31 20:29 UTC, YuriiStetsula requested changes

2020-08-31 20:29 UTC, YuriiStetsula commented on client/src/components/BarChart/BarChart.js
> +        debugger
remove

2020-08-31 20:29 UTC, YuriiStetsula commented on client/src/components/BarChart/BarChart.js
> +  debugger;
remove

2020-08-31 20:38 UTC, tarkus2000ua commented on client/src/components/BarChart/BarChart.js
> +        debugger
removed

2020-08-31 20:39 UTC, tarkus2000ua commented on client/src/components/BarChart/BarChart.js
> +  debugger;
removed

2020-09-02 06:52 UTC, YuriiStetsula approved these changes

2020-09-02 07:40 UTC, merged