Feature/collection/collection ui
BinaryStudioAcademy/bsa-2020-DaLi pull request #195
Opened 2020-09-03 23:34 UTC by Creatorbon

2020-09-04 16:19 UTC, ivanpatsaibinary requested changes

2020-09-04 21:46 UTC, Creatorbon commented on client/src/components/CollectionModal/modals/AddCollectionBody.js
> +      setFormData(values);
setSubmitting - standart formik function. In docs, they recommend to use it. [docs](https://formik.org/docs/api/formik#setsubmitting-issubmitting-boolean--void)

setFormData - action for saving data, from an edit form. And if we get an error from the server, we don't need to fill the form again

2020-09-04 21:47 UTC, Creatorbon commented on client/src/components/CollectionList/CollectionListItem.js
> +      {name === 'My personal collection' ? <StarIcon /> : <CollectionsIcon />}
I will make global constant

2020-09-05 12:37 UTC, Creatorbon commented on client/src/components/CollectionModal/modals/AddCollectionBody.js
> +      : formData,
done

2020-09-05 12:38 UTC, Creatorbon commented on client/src/components/CollectionList/CollectionListItem.js
> +      {name === 'My personal collection' ? <StarIcon /> : <CollectionsIcon />}
done

2020-09-05 14:33 UTC, YuriiStetsula approved these changes

2020-09-05 18:10 UTC, ivanpatsaibinary approved these changes

2020-09-05 18:36 UTC, merged